"""migration message

Revision ID: b4d96a98717e
Revises: 
Create Date: 2023-04-13 19:09:12.680338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4d96a98717e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('device_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('device_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('assigned_ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('date_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['mac_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('assigned_ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('device_type',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('device_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
